<p>&nbsp;</p>
<div class="container">
    <h3>Ingrese mes y a&ntilde;o a imprimir</h3>
    <div id="divpago">
        <form id="frmchoose" enctype="multipart/form-data" method="POST" action="/movimientos/prueba" class="form-horizontal" sytle="position: relative;">
            <div class="row">

                <div class="form-group">
                    <div class="col-md-1">
                        <label class="control-label">Socio</label>
                    </div>
                    <div class="col-md-2">
                        <input type="text" name='socio' id='socio' class="form-control" style="display: inline-block !important;">
                        <strong><span id="nombre">Name</span></strong>
                    </div>
                </div>
                <div class="tabla"></div>
                <div class="col-md-2">
                    <input id="imprimir" type="button" value="Imprimir" class="btn btn-primary"/>
                </div>
    
            </div>

        </form>
        <div>
            <table class="table table-bordered table-striped" id="items">
                <tr>
                    <th>Nro</th>
                    <th>Nombre</th>
                    <th>Mes</th>
                    <th>Año</th>
                    <th>Importe</th>
                </tr>
            </table>
        </div>
    </div>
</div>
<script>
    const $frm = document.querySelector("#frmchoose")
    const $tabla = document.querySelector(".tabla")
    const $items = document.querySelector("#items")
    const $nombre = document.querySelector("#nombre")
    const $socio = document.querySelector("#socio")
    const $print = document.querySelector("#imprimir")
    $socio.addEventListener('change', async evt => {
        const formData = new FormData
        formData.append('id', $socio.value)
        let res = await fetch('/socios/loadSocioAjax', {
            method: 'post',
            body: formData
        })
        let response = await res.json()
        $nombre.innerHTML = response.nombre
        formData.append('limit', 6)
        let req = await fetch('/movimientos/getSaldo', {
            method: 'post',
            body: formData
        })
        let respuesta = await req.json()
        let html = '<table class="table table-striped table-condensed"><tr><th>Mes</th><th>Año</th><th>Importe</th><th></th></tr>'
        let textoRes = respuesta.forEach(({mes, anio, importe}) => {
            html += `<tr><td>${mes}</td><td>${anio}</td><td>${importe}</td><td><a href="#" class="agregar">Agregar</a></td></tr>`
        })
        html += '</table>'
        document.querySelector('.tabla').innerHTML = html
    })

    $tabla.addEventListener('click', evt => {
        if(evt.target.nodeName === 'A') {
            const fila = evt.target.parentNode.parentNode
            const tr = document.createElement('tr')
            tr.setAttribute("class", "filas")
            let texto = `<td>${$frm.socio.value}</td>
                        <td>${document.querySelector("#nombre").innerHTML}</td>
                        <td>${fila.children[0].innerHTML}</td>
                        <td>${fila.children[1].innerHTML}</td>
                        <td>${fila.children[2].innerHTML}</td>
            `
            tr.innerHTML = texto
            $items.children[0].appendChild(tr)

            fila.parentNode.removeChild(fila)
        }
        
    })

    $print.addEventListener('click', async evt => {
        evt.preventDefault()
        let lista = document.querySelectorAll(".filas")
        let listPrint = [...lista]
        listFinal = listPrint.map( l => {
            return {id: l.children[0].innerHTML, mes: l.children[2].innerHTML, anio: l.children[3].innerHTML}
        })
        const str = JSON.stringify(listFinal)
        const elm = document.createElement('input')
        elm.setAttribute('type', 'hidden')
        elm.setAttribute('name', 'datos')
        elm.setAttribute('value', str)
        $frm.appendChild(elm)
        $frm.submit()
        
    })
</script>