<p>&nbsp;</p>
<div id="divpago" class="container">
    <h3 class="etiquetas">Ingrese mes y a&ntilde;o a generar</h3>
    <form id="form_pago" action="<?php echo BASE_URL . 'movimientos/generacuota' ?>" method="POST" class="form-horizontal">
        <div class="form-group">

            <label class="control-label col-md-2">Mes</label>
            <div class="col-md-4">

                <input type="text" name='mes' id='mes' class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">A&ntilde;o</label>
            <div class="col-md-4">
                <input type="text" name='anio' id='anio' class="form-control">

            </div>

        </div>

        <input type="submit" value="Generar" class="btn btn-primary"/>

    </form>

</div>
