<div class="container">
<h2><?php if($this->mensaje) echo $this->mensaje; ?></h2>

<p>&nbsp;</p>

<a href="<?php echo BASE_URL; ?>" class="btn btn-success">Ir al Inicio</a>
<a href="javascript:history.back(1)" class="btn btn-danger">Volver a la p&aacute;gina anterior</a>

<?php if(!Session::get('autenticado')): ?>

<a href="<?php echo BASE_URL . 'login'; ?>" class="btn btn-primary">Iniciar Sesi&oacute;n</a>

<?php endif; ?>
</div>